name: Publish npm package

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # If you have a build script

      - name: Authenticate to npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        run: npm publish
